INSERT INTO target_analytics.migration_column_mapping (migration_id,source_expression,target_column,transformation_expression,sequence_no) VALUES
	 (200,'BankTxtCode','bank_txt_code',NULL,1),
	 (200,'BankName','bank_name','trim(BankName)',2),
	 (200,'BankInitials','bank_initials',NULL,3),
	 (200,'CreatedDate','created_at',NULL,4),
	 (200,'LastUpdateDate','updated_at',NULL,5),
	 (200,'Deleted','deleted_at','CASE WHEN Deleted = true AND DeleteDate IS NOT NULL THEN DeleteDate WHEN Deleted = true AND DeleteDate IS NULL THEN CreatedDate ELSE NULL END',6),
	 (200,'BankCode','legacy_id','to_json(struct(BankCode AS bank_code, LastUpdateUser AS last_update_user))',7),
	 (300,'d.department','name',NULL,1),
	 (400,'m.name','name',NULL,1),
	 (100,'UserFullName','name',NULL,1),
	 (100,'CleanEmail','email','COALESCE(CleanEmail, CONCAT(UserCode, ''@legacy.local''))',2),
	 (100,'''''','password','''''',3),
	 (100,'UserName','username',NULL,4),
	 (100,'CreatedDate','created_at',NULL,5),
	 (100,'LastUpdateDate','updated_at',NULL,6),
	 (100,'Deleted','deleted_at','CASE WHEN Deleted = true AND DeleteDate IS NOT NULL THEN DeleteDate WHEN Deleted = true AND DeleteDate IS NULL THEN CreatedDate ELSE NULL END',7),
	 (100,'ContactNo','phone_no',NULL,8),
	 (100,'CreatedDate','terms_accepted_at',NULL,9),
	 (100,'''''','terms_accepted','1',10),
	 (100,'UserCode','legacy_id','concat(''{"db":"'',from_db,''","UserCode":"'',UserCode,''"}'')',11);
